version: "3.9"
services:
  api:
    image: tenable:gal
    build:
        context: .
        dockerfile: Dockerfile

    ports:
      - "8000:80"
    environment:
      - NEO4J_URI = 'bolt://neo4j:7687'
    networks:
      - app_network
  neo4j:
    image: neo4j:latest
    ports:
      - "7473:7473"
      - "7687:7687"
      - "7474:7474"
    environment:
        - NEO4J_AUTH=neo4j/password
        - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    working_dir: /var/lib/neo4j
    container_name: neo4j
    volumes:
      - ./data:/data
      - ./backups:/backups
      - ./backend/tests/test_db:/var/lib/neo4j/import
    networks:
      - app_network

volumes:
  neo4j_data:
networks:
  app_network:



